name: marvel_heroes
description: Projeto desenvolvido com base na atividade proposta no DevChallenge.
homepage: https://github.com/euferreira/marvel-heroes
repository: https://github.com/euferreira/marvel-heroes
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  crypto: ^3.0.1
  dartz: ^0.10.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chars/
    - assets/fonts/
    - assets/icons/
    - assets/movies/
    - assets/application.json
    - .env

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy-heavy.ttf
          weight: 800
        - asset: assets/fonts/gilroy-medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy-regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy-semibold.ttf
          weight: 600